language: clojure
dist: trusty
sudo: false
lein: 2.8.1

git:
  depth: 9999999

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - openjdk6
  - openjdk7
  - openjdk8
  - oraclejdk8
  - oraclejdk9

script: lein with-profile dev do check, test
