language: clojure
sudo: false
lein: 2.8.1

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - oraclejdk9
  - openjdk8
  - oraclejdk8
  - openjdk7
  - oraclejdk7
  - openjdk6

script: lein with-profile dev do check, test
