(ns clj-jgit.core
  (:require [clojure.java.io :as io]
            [clj-file-utils.core :as file]
            [clojure.contrib.repl-utils :as ru])
  (:import [org.eclipse.jgit.lib RepositoryBuilder]
           [org.eclipse.jgit.api
            Git
            InitCommand StatusCommand AddCommand
            ListBranchCommand]))

(defn load-repo
  "Given a path (either to the parent folder or to the `.git` folder itself), load the Git repository"
  [path]
  (let [dir (if (not (re-find #"\.git$" path))
              (io/as-file (str path "/.git"))
              (io/as-file path))]
    (when (.exists dir)
      (let [repo (-> (RepositoryBuilder.)
                     (.setGitDir dir)
                     (.readEnvironment)
                     (.findGitDir)
                     (.build))]
        (Git. repo)))))

(defn git-add
  "Given a repo and a pattern, add the files which match the pattern to the repo. If `only-update?` is set to `true`, only files which are already part of the index will have their changes staged (i.e. no previously untracked files will be added to the index)."
  ([repo file-pattern] (git-add repo file-pattern true))
  ([repo file-pattern only-update?]))

(defn git-branch-list
  "Get a list of branches in the Git repo. Return the default objects generated by the JGit API."
  ([repo] (git-branch-list* repo :local))
  ([repo opt]
     (let [opt-val {:all org.eclipse.jgit.api.ListBranchCommand$ListMode/ALL
                    :remote org.eclipse.jgit.api.ListBranchCommand$ListMode/REMOTE}
           branches (if (= opt :local)
                      (-> repo
                          (.branchList)
                          (.call))
                      (-> repo
                          (.branchList)
                          (.setListMode (opt opt-val))
                          (.call)))]
       (seq branches))))

(defn git-branch-create
  "Create a new branch in the Git repository."
  ([repo branch-name]        (git-branch-create repo branch-name false nil))
  ([repo branch-name force?] (git-branch-create repo branch-name force? nil))
  ([repo branch-name force? start-point]
     (if (nil? start-point)
       (-> repo
          (.branchCreate)
          (.setName branch-name)
          (.setForce force?)
          (.call))
       (-> repo
           (.branchCreate)
           (.setName branch-name)
           (.setForce force?)
           (.setStartPoint start-point)
           (.call)))))

(defn git-branch-delete
  ([repo branch-names] (git-branch-delete repo branch-names false))
  ([repo branch-names force?]
     (-> repo
         (.branchDelete)
         (.setBranchNames (into-array String branch-names))
         (.setForce force?)
         (.call))))

(defn git-branch [repo meth & opts]
  (let [branch-fns {:create #(.branchCreate %)
                    :delete #(.branchDelete %)
                    :list   #(.branchList %)}]))

(defn git-checkout [])
(defn git-cherry-pick [])
(defn git-clone [])
(defn git-fetch [])

(defn git-init
  "Initialize and load a new Git repository"
  ([] (git-init "."))
  ([target-dir]
     (let [comm (InitCommand.)]
       (-> comm
           (.setDirectory (io/as-file target-dir))
           (.call)))))

(defn git-log [])
(defn git-merge [])
(defn git-pull [])
(defn git-push [])
(defn git-rebase [])
(defn git-revert [])
(defn git-rm [])

(defn git-status
  "Return the status of the Git repository. Opts will return individual aspects of the status, and can be specified as `:added`, `:changed`, `:missing`, `:modified`, `:removed`, or `:untracked`."
  [repo & fields]
  (let [status (.. repo status call)
        status-fns {:added     #(.getAdded %)
                    :changed   #(.getChanged %)
                    :missing   #(.getMissing %)
                    :modified  #(.getModified %)
                    :removed   #(.getRemoved %)
                    :untracked #(.getUntracked %)}]
    (if-not (seq fields)
      (apply merge (for [[k f] status-fns]
                     {k (into #{} (f status))}))
      (apply merge (for [field fields]
                     {field (into #{} ((field status-fns) status))})))))

(defn git-tag [])