name: Run tests on push

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  clojure:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: "latest"
          lein: 2.9.1
          clj-kondo: 2023.05.26

      - name: Cache clojure deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('project.clj') }}
          restore-keys: cljdeps-

      - name: Get leiningen version
        run: lein -v

      - name: Setup master branch if it doesn't exist, referenced in some tests
        run: |
          [ ${GITHUB_REF_NAME} != 'master' ] && git fetch origin master:master || true

      - name: Run tests
        run: lein with-profile dev do check, test

      - name: Lint
        run: clj-kondo --fail-level error --parallel  --lint src --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
